/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "MyHTTP"
 */
package MyHTTP;

import java.util.Hashtable;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.type.AsnModule;
import org.asnlab.asndt.runtime.conv.*;


public class MyHTTP extends AsnModule {

	public final static Hashtable types = load(MyHTTP.class);

	public static AsnType type(int id) {
		return (AsnType) types.get(new Integer(id));
	}


}
