/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "MyHTTP"
 */
package MyHTTP;

import java.io.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;

public class Url {

	public static void ber_encode(String object, OutputStream out) throws IOException {
		TYPE.encode(object, EncodingRules.BASIC_ENCODING_RULES, CONVERTER, out);
	}

	public static String ber_decode(InputStream in) throws IOException {
		return (String)TYPE.decode(in, EncodingRules.BASIC_ENCODING_RULES, CONVERTER);
	}


	public final static AsnType TYPE = MyHTTP.type(65537);

	public final static AsnConverter CONVERTER = StringConverter.INSTANCE;


}
